#!/usr/bin/env python3
"""Convert a PSF2 bitmap font into a C source file with a flat glyph array.

Usage: psf2c.py <input.psf2> <symbol> <output.c>

The PSF2 header is eight little-endian 32-bit words:

    magic, version, headersize, flags, length, charsize, height, width

Glyphs follow the header as `length` blobs of `charsize` bytes, one byte per
pixel row, bit 7 = leftmost pixel.  PSF2 files carry no per-glyph Unicode map,
so the glyph order is the classic IBM code page 437 order that every 8x16 VGA
font uses.

Emitting `unsigned char` blobs (rather than a 2-D array) keeps the kernel's
freestanding C happy and lets the data be assembled straight out of a `.S`
file if ever needed.
"""

import sys


def main() -> int:
    if len(sys.argv) != 4:
        sys.stderr.write(__doc__)
        return 2
    src, symbol, dst = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(src, "rb") as fh:
        data = fh.read()

    if len(data) < 32:
        sys.stderr.write("psf2c: file too short to be PSF2\n")
        return 1

    def u32(off: int) -> int:
        return int.from_bytes(data[off:off + 4], "little")

    headersize = u32(8)
    flags = u32(12)
    length = u32(16)
    charsize = u32(20)
    height = u32(24)
    width = u32(28)

    if headersize != 32 or length == 0 or charsize == 0 or height == 0 or width == 0:
        sys.stderr.write(
            "psf2c: implausible PSF2 header "
            f"(headersize={headersize} length={length} charsize={charsize} "
            f"height={height} width={width})\n")
        return 1
    if charsize < height:
        sys.stderr.write("psf2c: charsize smaller than height\n")
        return 1

    table = data[headersize:headersize + length * charsize]
    if len(table) != length * charsize:
        sys.stderr.write("psf2c: glyph table truncated\n")
        return 1
    if flags & 1:
        # Unicode table present; we only consume the glyph bitmap data.
        sys.stderr.write("psf2c: ignoring trailing Unicode table\n")

    lines = [
        "/* Generated by tools/psf2c.py -- do not edit. */",
        f"/* source font: {src} */",
        f"/* {width}x{height} glyphs, code page 437 order */",
        "",
        f"#define {symbol.upper()}_WIDTH   {width}u",
        f"#define {symbol.upper()}_HEIGHT  {height}u",
        f"#define {symbol.upper()}_GLYPHS  {length}u",
        f"#define {symbol.upper()}_CHARSIZE {charsize}u",
        "",
        f"const unsigned char {symbol}[{length} * {charsize}] = {{",
    ]

    per_line = 16
    for gi in range(length):
        row = table[gi * charsize:(gi + 1) * charsize]
        cells = "".join(f"0x{b:02x}, " for b in row)
        lines.append(f"/* {gi:3d} */ {cells}")

    lines.append("};")
    lines.append("")

    with open(dst, "w") as fh:
        fh.write("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())